spring:
  datasource:
    ##会员数据库
    member:
        jdbc-url: jdbc:mysql://localhost:3306/user?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: lx@lx19870613
        driver: com.mysql.jdbc.Driver
    ##订单数据库
    order:
        jdbc-url: jdbc:mysql://localhost:3306/testorder?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: lx@lx19870613
        driver: com.mysql.jdbc.Driver