#spring:
#  datasource:
#    ##会员数据库
#    member:
#        jdbc-url: jdbc:mysql://localhost:3306/user?characterEncoding=UTF-8&serverTimezone=UTC
#        username: root
#        password: lx@lx19870613
#        driver: com.mysql.jdbc.Driver
#    ##订单数据库
#    order:
#        jdbc-url: jdbc:mysql://localhost:3306/testorder?characterEncoding=UTF-8&serverTimezone=UTC
#        username: root
#        password: lx@lx19870613
#        driver: com.mysql.jdbc.Driver

spring:
  datasource:
    member:
      url: jdbc:mysql://localhost:3306/user?characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: lx@lx19870613
      borrowConnectionTimeout: 30
      longinTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      maxLifetime: 20000
      maxPoolSize: 25
      minPoolSize: 3
      uniqueRresorceName: orderDataSource

    order:
        url: jdbc:mysql://localhost:3306/testorder?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: lx@lx19870613
        borrowConnectionTimeout: 30
        longinTimeout: 30
        maintenanceInterval: 60
        maxIdleTime: 60
        maxLifetime: 20000
        maxPoolSize: 25
        minPoolSize: 3
        uniqueRresorceName: memberDataSource

  profiles:
    active: dev
mayikt:
  userName: mayikt
